path: ../data/rdd2022-DatasetNinja/images
train:
- China_MotorBike/fold_0/images
- China_MotorBike/fold_2/images
- China_MotorBike/fold_3/images
val:
- China_MotorBike/fold_1/images

nc: 4
names:
  0: D00 - Longitudinal Crack
  1: D10 - Transverse Crack
  2: D20 - Alligator Crack
  3: D40 - Pothole
