path: ../data/rdd2022-DatasetNinja/images
train:
	- United_States/fold_0/images
	- United_States/fold_2/images
	- United_States/fold_3/images
val:
	- United_States/fold_1/images

nc: 4
names:
	0: D00 - Longitudinal Crack
	1: D10 - Transverse Crack
	2: D20 - Alligator Crack
	3: D40 - Pothole
