path: ../tfg-informatica/data/rdd2022-DatasetNinja
train:
- China_MotorBike/train/fold_1/images
- China_MotorBike/train/fold_2/images
- China_MotorBike/train/fold_3/images
val:
- China_MotorBike/train/fold_0/images

nc: 4
names:
  0: D00 - Longitudinal Crack
  1: D10 - Transverse Crack
  2: D20 - Alligator Crack
  3: D40 - Pothole
